ai:
  api_key: ''
  base_url: ''
  ecnu_key_file: D:\desktop\code\ICU\GraphCare\resources\ecnu.key
  max_tokens: 150
  model: ecnu-vl
  provider: ecnu
  temperature: 0.3
image:
  context_window: 2
  max_size_mb: 10
  supported_formats:
  - .png
  - .jpg
  - .jpeg
  - .gif
  - .bmp
  - .svg
  - .webp
logging:
  console: true
  file: reorganize.log
  level: INFO
naming:
  fallback_strategy: context_keywords
  max_length: 50
  remove_special_chars: true
  replace_spaces: _
  use_ai: true
organization:
  backup_suffix: _backup
  create_backup: true
  skip_existing: true
  update_links: true
